### PR TITLE
Ruby Clarifies User Vs. Account Tokens

### PR DESCRIPTION
**Pull request by jswright61**
Also allows Ruby command line argument to hit the Production API
Also fixes typo in CONTRIBUTING.markdown

### CODE REVIEW

**Comment by jswright61** [comment]
Totally your call. The scripts already provided comments for hitting production, I took it a step further. Note the default is to hit sandbox, to hit prod requires conscious action. I understand your concern and I will happily back out the changes if you'd prefer.

**Comment by aeden** [comment]
The purpose of the comment about connecting to production is more an explanation rather than an indication that this script should be used to hit production. Would you please remove the logic for connecting to production from the PR, and then I'll review again. Thanks.

**Comment by jswright61** [comment]
some typos - forcing update - please excuse for a moment

**Comment by jswright61** [comment]
Should be good now

**Comment by aeden** [comment]
Excellent! Thanks for taking the time to update the explanation, and for the account list example.

**Pull request merged**
